#!/usr/bin/env bash

set -e

if [ ! -f install ]; then
    echo 'install must be run within its container folder' 1>&2
    exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

if [ ! -d "src/github.com/studygolang/mux" ]; then
	go get -u -v github.com/studygolang/mux
fi

gofmt -w src

go install gox

export GOPATH="$OLDGOPATH"
export PATH="$OLDPATH"

echo 'finished'
