#!/usr/bin/env bash

set -e

if [ ! -f install ]; then
    echo 'install must be run within its container folder' 1>&2
    exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR:$CURDIR/../thirdparty"

if [ ! -d log ]; then
    mkdir log
fi

VERSION="`git symbolic-ref HEAD | cut -b 12-`-`git rev-parse HEAD`"
DATE=`date +%FT%T%z`

gofmt -w src

go install -ldflags "-X util/version.Version "$VERSION" -X util/version.Date "$DATE ./...

export GOPATH="$OLDGOPATH"
export PATH="$OLDPATH"

echo 'finished'
